// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    'IFluentEmojiHighContrast:disappointedFace': typeof import('~icons/fluent-emoji-high-contrast/disappointed-face')['default']
    'IFluentEmojiHighContrast:faceWithOpenEyesAndHandOverMouth': typeof import('~icons/fluent-emoji-high-contrast/face-with-open-eyes-and-hand-over-mouth')['default']
    IFluentEmojiHighContrastFaceWithOpenEyesAndHandOverMouth: typeof import('~icons/fluent-emoji-high-contrast/face-with-open-eyes-and-hand-over-mouth')['default']
    IHeroiconsRocketLaunchSolid: typeof import('~icons/heroicons/rocket-launch-solid')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
